import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
      <nav>
        <ul>
          <li><Link href="/">홈</Link></li>
          <li> <Link href="/about">소개</Link></li>
          <li><Link href="/article">게시판</Link></li>
          <li><Link href="/member/login">로그인</Link></li>
        </ul>
      </nav>
        {children}
      </body>
    </html>
  );
}